# Generated by Django 3.2.9 on 2022-01-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220124_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildinevidence',
            old_name='task',
            new_name='engagment',
        ),
        migrations.RenameField(
            model_name='uploadedevidence',
            old_name='task',
            new_name='engagment',
        ),
    ]
