# Generated by Django 3.2.9 on 2021-12-17 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildinEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('preparer', models.ForeignKey(limit_choices_to={'is_staff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='buildin_evidence_preparer', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(limit_choices_to={'is_staff': False, 'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='buildin_evidence_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='tasks_files')),
                ('note', models.TextField()),
                ('preparer', models.ForeignKey(limit_choices_to={'is_staff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_evidence_preparer', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(limit_choices_to={'is_staff': False, 'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_evidence_reviewer', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descripion', models.TextField()),
                ('engagment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagment.engagment')),
                ('user_create', models.ForeignKey(limit_choices_to={'is_staff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskgroup'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.buildinevidence')),
            ],
        ),
        migrations.AddField(
            model_name='buildinevidence',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
