# Generated by Django 3.2.9 on 2022-01-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagment', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinevidence',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagment.engagment'),
        ),
        migrations.AlterField(
            model_name='uploadedevidence',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagment.engagment'),
        ),
    ]
