# Generated by Django 3.2.9 on 2022-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20220124_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinevidence',
            name='content',
            field=models.TextField(default='lfqskjflkqsjflkjlkjsqlfkjqslfkjlqsfkj'),
            preserve_default=False,
        ),
    ]
