# Generated by Django 3.2.9 on 2022-02-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_buildinevidence_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='descripion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
