# Generated by Django 3.2.9 on 2022-02-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_taskgroup_descripion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildinevidence',
            name='content',
        ),
        migrations.AddField(
            model_name='buildinevidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks_files'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
