# Generated by Django 3.2.9 on 2022-02-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220206_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildinevidence',
            name='engagment',
        ),
        migrations.RemoveField(
            model_name='uploadedevidence',
            name='engagment',
        ),
        migrations.AddField(
            model_name='buildinevidence',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildinevidence',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AddField(
            model_name='uploadedevidence',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AlterField(
            model_name='uploadedevidence',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
