# Generated by Django 3.2.9 on 2022-02-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20220206_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinevidence',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AlterField(
            model_name='uploadedevidence',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
