# Generated by Django 3.2.9 on 2022-02-07 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0010_auto_20220206_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildinevidence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='buildinevidence',
            name='preparer',
        ),
        migrations.RemoveField(
            model_name='buildinevidence',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='buildinevidence',
            name='task',
        ),
        migrations.AddField(
            model_name='buildinevidence',
            name='content',
            field=models.TextField(default='kmjlkjlkj'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparer', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildin_evidence_preparer', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'is_staff': False, 'is_superuser': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildin_evidence_reviewer', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.AddField(
            model_name='buildinevidence',
            name='section',
            field=models.ManyToManyField(to='task.Section'),
        ),
    ]
