# Generated by Django 3.2.9 on 2022-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20220207_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildinevidence',
            name='section',
        ),
        migrations.AddField(
            model_name='buildinevidence',
            name='title',
            field=models.CharField(default='llhlh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='evidence',
            field=models.ManyToManyField(blank=True, null=True, to='task.BuildinEvidence'),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default='khljhkj', max_length=100),
            preserve_default=False,
        ),
    ]
