name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "task-manager-api-f"
          heroku_email: ${{ secrets.EMAIL }}
          procfile: "web: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
          healthcheck: "https://task-manager-api-f.herokuapp.com/health"